version: '3'

vars:
  BINARY_NAME: reddit-kv
  BUILD_DIR: ./bin
  MAIN_PKG: ./cmd/reddit-kv

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  test:short:
    desc: Run tests (short output)
    cmds:
      - go test ./...

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PKG}}
    sources:
      - ./**/*.go
    generates:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'

  install:
    desc: Install binary to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PKG}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out

  run:
    desc: Run the CLI (pass args after --)
    cmds:
      - go run {{.MAIN_PKG}} {{.CLI_ARGS}}

  # Composite tasks
  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test:short

  all:
    desc: Tidy, check, and build
    cmds:
      - task: tidy
      - task: check
      - task: build
